<?php
/**
 * Defining variables used in html.
 *
 * @var $title string
 * @var $content string
 */
?>
<!DOCTYPE html>
<html lang="ru">
	<head>
		<title><?=$title?></title>
		<meta http-equiv="Content-type" content="charset=utf-8" />
		<meta name="description" content="This is the main page of my site"/>
		<link rel="icon" href="/web/img/favicon.ico" type="image/x-icon">
		<link rel="stylesheet" href="/web/css/style.css" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Comfortaa:400,300,700&subset=latin,cyrillic,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css'/>
	</head>
	<body>
		<div class="wrapper">
			<div class="content">
				<ul class="main-menu">
					<li>
						<h1><a href="/">Home</a></h1>
					</li>
				</ul>
				<section>
					<?=$content?>
				</section>
			</div>
			
			<footer>
				All rights reserved &copy; 2018
			</footer>
		</div>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<!--		<script src="/web/js/handler.js"></script>-->
	
	</body>
</html>